Aggiunti bottoni per comandi
tsi-unito/menu_bot pull request #32
Opened 2023-10-26 17:43 UTC by lorenzodipi

2023-10-27 17:10 UTC, lory9894 commented on bot.py
> +        await menu_command(update, context)
il comando menu_command si aspetta che il comando scritto dall'utente sia formattato così: menu__nomeristorante_

In questo caso gli viene passato "start dubai" e non è in grado di parsarlo. Bisogna aggiustare il parsing di menu_command oppure modificare il context che viene passato al metodo

2023-10-27 17:10 UTC, lory9894 commented on bot.py
> +    elif text == 'stop dubai' or text == 'stop doc':
stesso discorso vale per unsubscription_command

2023-10-27 17:11 UTC, lory9894 requested changes
il codice non è funzionante così, ho lasciato dei commenti che spiegano come mai non funziona, se hai bisogno di indicazioni su come runnare il progetto per poterlo testare scrivimi che ne parliamo

2023-10-31 13:17 UTC, lorenzodipi commented
Errore mio, ho risolto

2023-11-01 16:51 UTC, lory9894 commented
ok, adesso mi sembra tutto corretto

Ci sono però dei comandi (help, stop, autori e FAQ) che non fanno nulla. 
Finchè non creaiamo le funzionalità li togliamo dalla lista?

2023-11-01 16:57 UTC, lory9894 approved these changes

2023-11-01 16:58 UTC, lory9894 commented
@lorenzodipi lascio la pull request aperta per chiarire questo dubbio, però ho fatto la review ed approvato la PR

2023-11-01 17:41 UTC, lorenzodipi commented
@lory9894 essendo dei comandi che dovremmo mettere lì ho già scritto, a questo punto li lascerei così che ce li ritroviamo già quando poi li creeremo. Anzi potremmo anche farlo subito non essendo cose difficili.

2023-11-03 10:29 UTC, merged